export default {
   'activity-city-select': '城市选择 CitySelect',
               'activity-downloader': '下载Bar',
         'activity-exchange': '兑换 Exchange',
        'activity-marquee': '跑马灯 Marquee',
'activity-ranklist': '主播排行榜组件 ranklist',
                'activity-reward': 'reward',
             'activity-rule': '规则 Rule',
        'activity-tab': '选项卡组件 Tab',
   'activity-titlebar': '顶部标题栏 titlebar',

                'base-apptoast': 'AppToast',
                  'base-avatar': 'Avatar',
                  'base-button': 'Button',
                   'base-cover': 'Cover',
          'base-dialog_Dialog1': 'Dialog 样式1',
          'base-dialog_Dialog2': 'Dialog 样式2',
          'base-dialog_Dialog3': 'Dialog 样式3',
                   'base-empty': 'Empty',
                    'base-icon': 'Icon',
                  'base-layout': 'Layout',
                'base-lazyload': 'Lazyload',
                    'base-list': 'List',
                 'base-loading': 'Loading',
                   'base-toast': 'Toast',
                   'base-topic': 'Topic',

       'display-banner': 'Banner 无限滚动',
       'display-bubble': 'Bubble 点赞动画',
    'display-combogift': 'ComboGift 连击礼物',
   'display-controlBar': 'ControlBar 控制面板',
 'display-controlpanel': 'ControlPanel 控制面板',
   'display-customgift': 'CustomGift 个性礼物',
'display-downloadbar': 'Downloadbar 下载进度条',
    'display-giftpanel': 'GiftPanel 礼物面板',
       'display-header': 'Header 顶部信息',
   'display-luxurygift': 'LuxuryGift 豪华礼物',
          'display-message': 'Message 信息',
      'display-offline': 'Offline 直播结束',
     'display-player': 'Player 直播播放器',
    'display-pylon': 'Pylon 动态加载组件',
     'display-ranklist': 'Ranklist 排名列表',
    'display-recommend': 'Recommend 推荐列表',
     'display-record': 'Record 录播播放器',
   'display-sharepanel': 'SharePanel 分享面板',
      'display-userprofile': 'Profile 用户信息',
      'display-video': 'Video 直播播放器'
};